# docker-compose.yml
version: '3'

services:
  jupyter_spark:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tomasteawita_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./docker_shared_folder/working_dir:/home/tomasteawita/working_dir
    user: root
    working_dir: /home/tomasteawita/working_dir
    env_file:
      - ./docker_shared_folder/.env
    environment:
      NB_USER: tomasteawita
      NB_GID: 1000
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'
      SPARK_CLASSPATH: '/home/tomasteawita/working_dir/spark_drivers/postgresql-42.5.2.jar'
    networks:
      tomasteawita_net:
        ipv4_address: 172.7.7.1

  postgres:
    container_name: tomasteawita_postgres
    image: 'postgres:15'
    hostname: postgres_host
    volumes:
      - ./docker_shared_folder/postgres_data:/var/lib/postgresql/data
    ports:
      - 5435:5435
    command: "-p 5435"
    env_file:
      - ./docker_shared_folder/.env
    networks:
      tomasteawita_net:
        ipv4_address: 172.7.7.2


networks:
  tomasteawita_net: 
    ipam: 
      driver: default
      config:
        - subnet: 172.7.7.0/16